[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
EarthOrientation = "732a3c5d-d6c0-58bc-adb1-1b51709a25e2"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
SOFA = "ad3d3fd0-b5f2-51ee-b274-8cdbe62317e2"
SatelliteDynamics = "0e7c1a32-1b9f-5532-88a4-e668712d6a4c"
SatelliteToolbox = "6ac157d9-b43d-51bb-8fab-48bf53814f4a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
